version: '3.8'

services:
  api:
    image: abanoubhany/expansion-management-api:prebuilt
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=expansion_management
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MONGO_URI=mongodb://mongo:27017/expansion_management
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=production
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped

  updater:
    image: alpine/git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repo:/repo
    command: >
      sh -c "
      cd /repo &&
      git clone https://github.com/h4775346/expansion-management-api.git . ||
      (cd /repo && git pull origin main) &&
      sleep 3600
      "
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expansion_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data: